### PR TITLE
feat(deployers): init pool script

### PR DESCRIPTION
**Pull request by dleonard00**

### CODE REVIEW

**Comment by dleonard00** [comment]
There's not an good way to test new workflows. Merging this to be able to test it.

**Comment by paulrberg** [comment]
There's a couple of issues introduced by this PR.

- The "add liquidity" workflow is not a deployer. We have to either rename the `deployers` package to something else (e.g. `scripts`) or move all the "deployers" to the `helpers` package.
- The `TASK_ADD_LIQUIDITY` constant is not ordered alphabetically in the `constants.ts` file
- There's a lot of logic in the `addLiquidity.ts`, some of which is not easy to understand at first blush. We should group the code and and add annotations.

I will handle these myself.

**Comment by paulrberg** [comment]
Further issues:

- The comparison between the big numbers is done with the `>=` operator. This is, as far as I know, prone to errors. We should instead use the `gt`, `gte`, `lt` and `lte` functions shipped with `@ethersproject/bignumber`.
- In a similar vein, multiplication is done via the vanilla `*` JavaScript operator. When working with big numbers, we should always use the `mul` function shipped with the `BigNumber` class.
- Continuous integration is failing, because the lint step is failing. Issue is that there are some unused variables.
- The `hTokenRatio` is unnecessary, and at any rate doesn't map onto the existing naming system. We call the "ratio" a "scalar".

**Comment by paulrberg** [comment]
And another big big issue:

The task is calling the `HifiProxyTarget`, though that is supposed to be called only via the DSProxy.

**Pull request merged**
