### PR TITLE
feat(proxy-target): accept eip2612 signatures

### PR DESCRIPTION
**Pull request by surbhiaudichya**

### CODE REVIEW

**Comment by paulrberg** [comment]
Thanks for this PR, @surbhiaudichya. Before I can review it though, you will have to resolve the git conflicts. You can do that by manually removing the "src/types" directory and re-generating the types via the `generate:types` script. The reason why types don't use the `.d.ts` file extension anymore is that the latest version of TypeChain switched to pure `.ts` extensions in their type generation algorithm.

Also, before this can be used at all, we'd have to switch from `@paulrberg/contracts` to `@prb/contracts` - since in [v3.8.0](https://github.com/paulrberg/prb-contracts/releases/tag/v3.8.0) I changed the name of the package. I will handle this part myself.

**Comment by surbhiaudichya** [comment]
@paulrberg  I re-generating the types via the` generate:types` script for the latest version of TypeChain.

**Comment by paulrberg** [comment]
Yes but you also have to resolve the git conflicts before I can review this.

**Comment by surbhiaudichya** [comment]
@paulrberg branch has no conflicts with the base branch now but some of the checks are still failing, I am looking into it.

**Comment by paulrberg** [comment]
@surbhiaudichya Checks are failing because of the `yarn install --immutable` command. The [immutable](https://yarnpkg.com/cli/install#options) flag ensures that the `yarn.lock` file does not get modified in CI.

**Comment by surbhiaudichya** [comment]
@paulrberg Sure, I can do that.

**Pull request closed without merging**
